// Bilingual content for Kamel Landing Page
const content = {
    en: {
        nav: {
            logo: "Kamel",
            platform: "Platform",
            solutions: "Solutions",
            pricing: "Pricing",
            contact: "Contact",
            cta: "Schedule a Demo"
        },
        hero: {
            overline: "Complete Hajj Operations Platform",
            headline: "Excellence in Every Journey",
            subheadline: "Streamline operations, ensure compliance, and deliver exceptional service with Saudi Arabia's most trusted Hajj management platform.",
            primaryCta: "Talk to Our Team",
            secondaryCta: "Schedule a Demo",
            trustBadge: "Trusted by 500+ Hajj operators • Enterprise-grade platform",
            stat1Value: "500+",
            stat1Label: "Hajj Operators",
            stat2Value: "1M+",
            stat2Label: "Pilgrims Served",
            stat3Value: "99.9%",
            stat3Label: "Uptime"
        },
        social: {
            trusted: "Trusted by Leading Hajj Operators"
        },
        features: {
            tag: "Platform Capabilities",
            title: "Everything You Need in One Platform",
            subtitle: "Comprehensive tools designed specifically for Hajj operations, ensuring excellence at every step",
            learnMore: "Learn more",
            feature1Title: "Operations Hub",
            feature1Desc: "Real-time dashboards, automated workflows, and comprehensive tracking for complete operational control.",
            feature2Title: "Smart Logistics",
            feature2Desc: "GPS tracking, intelligent routing, and capacity optimization for seamless transportation and accommodation management.",
            feature3Title: "Compliance Engine",
            feature3Desc: "Automated compliance checks, quality assurance workflows, and instant reporting for government standards.",
            feature4Title: "Communication Suite",
            feature4Desc: "Multi-channel messaging, automated notifications, and real-time updates to keep everyone connected.",
            feature5Title: "Analytics & Insights",
            feature5Desc: "Powerful analytics, custom reports, and data-driven insights to optimize your operations continuously.",
            feature6Title: "Mobile First",
            feature6Desc: "Full-featured mobile apps for iOS and Android, enabling management from anywhere, anytime."
        },
        solutions: {
            title: "Solutions for Every Challenge",
            subtitle: "Purpose-built tools to address the unique challenges of Hajj operations",
            solution1Tag: "Problem",
            solution1Title: "Scattered Information Across Multiple Systems",
            solution1Problem: "Hajj operators struggle with managing data across spreadsheets, emails, and disconnected tools, leading to errors and inefficiencies.",
            solution1SolutionTag: "Solution",
            solution1Solution: "Kamel unifies all operations in one centralized platform with real-time data synchronization and intelligent automation.",
            solution1Benefit1: "Single source of truth for all operations data",
            solution1Benefit2: "Automated workflows eliminate manual data entry",
            solution1Benefit3: "Real-time visibility across all teams and locations",
            solution2Tag: "Problem",
            solution2Title: "Complex Logistics and Coordination Challenges",
            solution2Problem: "Managing transportation, accommodations, and schedules for thousands of pilgrims requires precise coordination and real-time adjustments.",
            solution2SolutionTag: "Solution",
            solution2Solution: "Smart logistics management with GPS tracking, capacity planning, and automated scheduling optimization.",
            solution2Benefit1: "Real-time bus and vehicle tracking",
            solution2Benefit2: "Intelligent room allocation and capacity management",
            solution2Benefit3: "Automated schedule adjustments and notifications",
            solution3Tag: "Problem",
            solution3Title: "Meeting Government Standards and Regulations",
            solution3Problem: "Complying with Ministry requirements and quality standards demands extensive documentation and regular audits.",
            solution3SolutionTag: "Solution",
            solution3Solution: "Built-in compliance framework with automated reporting, quality checklists, and audit trail management.",
            solution3Benefit1: "Pre-configured compliance templates",
            solution3Benefit2: "Automatic report generation for authorities",
            solution3Benefit3: "Complete audit trail for all operations"
        },
        testimonials: {
            tag: "Client Success",
            title: "Trusted by Leading Operators",
            subtitle: "Real results from Hajj operators who transformed their operations with Kamel",
            testimonial1Name: "Ahmed Al-Rashid",
            testimonial1Title: "Operations Director",
            testimonial1Company: "Al-Noor Hajj Services",
            testimonial1Quote: "Kamel has revolutionized how we manage our Hajj operations. The real-time tracking and automated workflows have reduced our operational costs by 40% while improving service quality.",
            testimonial2Name: "Fatima Al-Zahrani",
            testimonial2Title: "CEO",
            testimonial2Company: "Excellence Hajj Group",
            testimonial2Quote: "The compliance features alone are worth it. We now generate all required reports automatically and have complete confidence in meeting government standards. Highly recommended!",
            testimonial3Name: "Mohammed bin Saud",
            testimonial3Title: "Logistics Manager",
            testimonial3Company: "Premium Hajj Solutions",
            testimonial3Quote: "Transportation management has never been easier. We track all our buses in real-time and our pilgrims receive automatic updates. Customer satisfaction has improved dramatically."
        },
        pricing: {
            tag: "Investment in Excellence",
            title: "Scale At Your Pace",
            subtitle: "Transparent, value-driven packages designed to grow with your operations—from boutique operators to enterprise-scale organizations",
            popularBadge: "Recommended for Most",
            plan2Name: "Professional",
            plan2Desc: "For growing Hajj operators ready to scale operations and enhance service delivery",
            plan2Capacity: "Up to 5,000 pilgrims",
            plan2Contact: "Custom pricing based on your needs",
            plan2Value1Title: "Rapid Deployment",
            plan2Value1: "Go live in 2-4 weeks with dedicated onboarding",
            plan2Value2Title: "Compliance Included",
            plan2Value2: "All Ministry standards automated",
            plan2Value3Title: "24/7 Support",
            plan2Value3: "Priority assistance in Arabic & English",
            plan2Value4Title: "Analytics Dashboard",
            plan2Value4: "Real-time insights & reporting",
            plan2Cta: "Discuss Your Needs",
            plan3Name: "Enterprise",
            plan3Desc: "For large-scale operators managing thousands of pilgrims with complex requirements",
            plan3Price: "Custom",
            plan3PriceDesc: "Tailored to your scale & requirements",
            plan3Feature1: "Unlimited capacity",
            plan3Feature2: "Dedicated account manager",
            plan3Feature3: "Custom integrations & API",
            plan3Feature4: "On-premise deployment option",
            plan3Feature5: "White-label options",
            plan3Cta: "Contact Our Team"
        },
        faq: {
            tag: "Common Questions",
            title: "Everything You Need to Know",
            subtitle: "Quick answers to questions you may have about Kamel",
            question1: "How quickly can we implement Kamel?",
            answer1: "Implementation typically takes 2-4 weeks depending on your organization's size and complexity. Our team provides full onboarding support, training, and data migration assistance to ensure a smooth transition.",
            question2: "Is Kamel compliant with Saudi government regulations?",
            answer2: "Yes, Kamel is fully compliant with Ministry of Hajj and Umrah regulations. We regularly update our platform to meet all government standards and requirements for Hajj service providers.",
            question3: "Can we integrate Kamel with our existing systems?",
            answer3: "Absolutely. Kamel offers API access for Professional and Enterprise plans, allowing seamless integration with your existing CRM, accounting, and other business systems.",
            question4: "What kind of support do you provide?",
            answer4: "We offer email support for all plans, with 24/7 priority support for Professional and Enterprise customers. Enterprise clients also receive a dedicated account manager and on-site training if needed.",
            question5: "Is mobile access included?",
            answer5: "Yes, Kamel includes mobile apps for both iOS and Android for all plans. Your team can manage operations on the go, and pilgrims can access their information through a dedicated pilgrim app.",
            question6: "How secure is our data?",
            answer6: "Security is our top priority. We use enterprise-grade encryption, regular security audits, and comply with international data protection standards. All data is backed up daily with disaster recovery protocols in place."
        },
        contact: {
            tag: "Get in Touch",
            title: "Let's Discuss Your Needs",
            subtitle: "Schedule a consultation with our team to see how Kamel can transform your Hajj operations",
            nameLabel: "Full Name",
            namePlaceholder: "Your full name",
            emailLabel: "Email Address",
            emailPlaceholder: "your@email.com",
            companyLabel: "Company/Organization",
            companyPlaceholder: "Your company name",
            messageLabel: "Message",
            messagePlaceholder: "Tell us about your needs...",
            submitButton: "Send Message",
            successMessage: "Thank you! We'll get back to you shortly.",
            errorMessage: "Something went wrong. Please try again."
        },
        footer: {
            description: "Transforming Hajj operations through innovative digital solutions.",
            quickLinksTitle: "Quick Links",
            features: "Features",
            solutions: "Solutions",
            pricing: "Pricing",
            testimonials: "Testimonials",
            supportTitle: "Support",
            contact: "Contact Us",
            faq: "FAQ",
            help: "Help Center",
            documentation: "Documentation",
            legalTitle: "Legal",
            privacy: "Privacy Policy",
            terms: "Terms of Service",
            copyright: "© 2024 Kamel. All rights reserved."
        }
    },
    ar: {
        nav: {
            logo: "كامل",
            platform: "المنصة",
            solutions: "الحلول",
            pricing: "الأسعار",
            contact: "تواصل معنا",
            cta: "حدد موعد عرض توضيحي"
        },
        hero: {
            overline: "منصة متكاملة لإدارة عمليات الحج",
            headline: "التميز في كل رحلة",
            subheadline: "قم بتبسيط العمليات، وضمان الامتثال، وتقديم خدمة استثنائية مع المنصة الأكثر موثوقية لإدارة الحج في المملكة العربية السعودية.",
            primaryCta: "تحدث مع فريقنا",
            secondaryCta: "حدد موعد عرض توضيحي",
            trustBadge: "موثوق به من قبل أكثر من 500 مشغل حج • منصة على مستوى المؤسسات",
            stat1Value: "500+",
            stat1Label: "مشغل حج",
            stat2Value: "+1 مليون",
            stat2Label: "حاج تمت خدمته",
            stat3Value: "99.9%",
            stat3Label: "وقت التشغيل"
        },
        social: {
            trusted: "موثوق به من قبل كبار مشغلي الحج"
        },
        features: {
            tag: "قدرات المنصة",
            title: "كل ما تحتاجه في منصة واحدة",
            subtitle: "أدوات شاملة مصممة خصيصاً لعمليات الحج، لضمان التميز في كل خطوة",
            learnMore: "اعرف المزيد",
            feature1Title: "مركز العمليات",
            feature1Desc: "لوحات معلومات في الوقت الفعلي، سير عمل آلي، وتتبع شامل للتحكم الكامل في العمليات.",
            feature2Title: "لوجستيات ذكية",
            feature2Desc: "تتبع GPS، توجيه ذكي، وتحسين السعة لإدارة سلسة للنقل والإقامة.",
            feature3Title: "محرك الامتثال",
            feature3Desc: "فحوصات امتثال آلية، سير عمل لضمان الجودة، وإعداد تقارير فورية للمعايير الحكومية.",
            feature4Title: "حزمة الاتصالات",
            feature4Desc: "مراسلة متعددة القنوات، إشعارات آلية، وتحديثات في الوقت الفعلي لإبقاء الجميع على اتصال.",
            feature5Title: "التحليلات والرؤى",
            feature5Desc: "تحليلات قوية، تقارير مخصصة، ورؤى مدفوعة بالبيانات لتحسين عملياتك باستمرار.",
            feature6Title: "الجوال أولاً",
            feature6Desc: "تطبيقات جوال كاملة المزايا لنظامي iOS و Android، تمكنك من الإدارة من أي مكان وفي أي وقت."
        },
        solutions: {
            title: "حلول لكل تحدي",
            subtitle: "أدوات مصممة خصيصاً لمواجهة التحديات الفريدة لعمليات الحج",
            solution1Tag: "المشكلة",
            solution1Title: "تشتت المعلومات عبر أنظمة متعددة",
            solution1Problem: "يواجه مشغلو الحج صعوبة في إدارة البيانات عبر جداول البيانات والبريد الإلكتروني والأدوات غير المتصلة، مما يؤدي إلى أخطاء وعدم كفاءة.",
            solution1SolutionTag: "الحل",
            solution1Solution: "يوحد كامل جميع العمليات في منصة مركزية واحدة مع مزامنة البيانات في الوقت الفعلي والأتمتة الذكية.",
            solution1Benefit1: "مصدر واحد للحقيقة لجميع بيانات العمليات",
            solution1Benefit2: "سير العمل الآلي يلغي إدخال البيانات يدوياً",
            solution1Benefit3: "رؤية في الوقت الفعلي عبر جميع الفرق والمواقع",
            solution2Tag: "المشكلة",
            solution2Title: "تحديات الخدمات اللوجستية والتنسيق المعقدة",
            solution2Problem: "تتطلب إدارة النقل والإقامة والجداول الزمنية لآلاف الحجاج تنسيقاً دقيقاً وتعديلات في الوقت الفعلي.",
            solution2SolutionTag: "الحل",
            solution2Solution: "إدارة لوجستية ذكية مع تتبع GPS وتخطيط القدرات وتحسين الجدولة الآلية.",
            solution2Benefit1: "تتبع الحافلات والمركبات في الوقت الفعلي",
            solution2Benefit2: "تخصيص ذكي للغرف وإدارة السعة",
            solution2Benefit3: "تعديلات تلقائية للجدول الزمني والإشعارات",
            solution3Tag: "المشكلة",
            solution3Title: "الامتثال للمعايير واللوائح الحكومية",
            solution3Problem: "يتطلب الامتثال لمتطلبات الوزارة ومعايير الجودة توثيقاً واسع النطاق وعمليات تدقيق منتظمة.",
            solution3SolutionTag: "الحل",
            solution3Solution: "إطار امتثال مدمج مع إعداد التقارير الآلية وقوائم التحقق من الجودة وإدارة سجل التدقيق.",
            solution3Benefit1: "قوالب امتثال مُعدة مسبقاً",
            solution3Benefit2: "إنشاء تقارير تلقائية للسلطات",
            solution3Benefit3: "سجل تدقيق كامل لجميع العمليات"
        },
        testimonials: {
            tag: "نجاح العملاء",
            title: "موثوق به من قبل كبار المشغلين",
            subtitle: "نتائج حقيقية من مشغلي الحج الذين حولوا عملياتهم مع كامل",
            testimonial1Name: "أحمد الراشد",
            testimonial1Title: "مدير العمليات",
            testimonial1Company: "خدمات الحج النور",
            testimonial1Quote: "لقد أحدث كامل ثورة في كيفية إدارتنا لعمليات الحج. لقد قلل التتبع في الوقت الفعلي وسير العمل الآلي من تكاليف التشغيل بنسبة 40٪ مع تحسين جودة الخدمة.",
            testimonial2Name: "فاطمة الزهراني",
            testimonial2Title: "الرئيس التنفيذي",
            testimonial2Company: "مجموعة الحج المتميزة",
            testimonial2Quote: "ميزات الامتثال وحدها تستحق ذلك. نحن الآن ننشئ جميع التقارير المطلوبة تلقائياً ولدينا ثقة كاملة في تلبية المعايير الحكومية. موصى به بشدة!",
            testimonial3Name: "محمد بن سعود",
            testimonial3Title: "مدير اللوجستيات",
            testimonial3Company: "حلول الحج الممتازة",
            testimonial3Quote: "لم تكن إدارة النقل أسهل من أي وقت مضى. نتتبع جميع حافلاتنا في الوقت الفعلي ويتلقى حجاجنا تحديثات تلقائية. تحسنت رضا العملاء بشكل كبير."
        },
        pricing: {
            tag: "الاستثمار في التميز",
            title: "التوسع بالوتيرة التي تناسبك",
            subtitle: "حزم شفافة قائمة على القيمة مصممة للنمو مع عملياتك—من المشغلين المتخصصين إلى المؤسسات واسعة النطاق",
            popularBadge: "موصى به للأغلبية",
            plan2Name: "المحترف",
            plan2Desc: "لمشغلي الحج المتنامين المستعدين لتوسيع العمليات وتحسين تقديم الخدمات",
            plan2Capacity: "ما يصل إلى 5,000 حاج",
            plan2Contact: "تسعير مخصص بناءً على احتياجاتك",
            plan2Value1Title: "النشر السريع",
            plan2Value1: "انطلق في 2-4 أسابيع مع تأهيل مخصص",
            plan2Value2Title: "الامتثال مضمن",
            plan2Value2: "جميع معايير الوزارة آلية",
            plan2Value3Title: "دعم 24/7",
            plan2Value3: "مساعدة ذات أولوية بالعربية والإنجليزية",
            plan2Value4Title: "لوحة التحليلات",
            plan2Value4: "رؤى وتقارير في الوقت الفعلي",
            plan2Cta: "ناقش احتياجاتك",
            plan3Name: "المؤسسات",
            plan3Desc: "للمشغلين واسعي النطاق الذين يديرون آلاف الحجاج مع متطلبات معقدة",
            plan3Price: "مخصص",
            plan3PriceDesc: "مصمم خصيصاً لحجمك ومتطلباتك",
            plan3Feature1: "سعة غير محدودة",
            plan3Feature2: "مدير حساب مخصص",
            plan3Feature3: "تكاملات وAPI مخصصة",
            plan3Feature4: "خيار النشر المحلي",
            plan3Feature5: "خيارات العلامة البيضاء",
            plan3Cta: "تواصل مع فريقنا"
        },
        faq: {
            tag: "أسئلة شائعة",
            title: "كل ما تحتاج لمعرفته",
            subtitle: "إجابات سريعة للأسئلة التي قد تكون لديك حول كامل",
            question1: "ما مدى سرعة تنفيذ كامل؟",
            answer1: "يستغرق التنفيذ عادةً من 2 إلى 4 أسابيع حسب حجم مؤسستك وتعقيدها. يقدم فريقنا دعماً كاملاً للتأهيل والتدريب ومساعدة في ترحيل البيانات لضمان انتقال سلس.",
            question2: "هل كامل متوافق مع اللوائح الحكومية السعودية؟",
            answer2: "نعم، كامل متوافق تماماً مع لوائح وزارة الحج والعمرة. نقوم بتحديث منصتنا بانتظام لتلبية جميع المعايير والمتطلبات الحكومية لمقدمي خدمات الحج.",
            question3: "هل يمكننا دمج كامل مع أنظمتنا الحالية؟",
            answer3: "بالتأكيد. يوفر كامل وصولاً إلى API للخطط الاحترافية والمؤسسية، مما يسمح بالتكامل السلس مع أنظمة CRM والمحاسبة والأعمال الأخرى الموجودة لديك.",
            question4: "ما نوع الدعم الذي تقدمونه؟",
            answer4: "نقدم دعماً عبر البريد الإلكتروني لجميع الخطط، مع دعم ذو أولوية على مدار الساعة طوال أيام الأسبوع للعملاء المحترفين والمؤسسيين. يتلقى عملاء المؤسسات أيضاً مدير حساب مخصص وتدريب في الموقع إذا لزم الأمر.",
            question5: "هل الوصول عبر الهاتف المحمول مشمول؟",
            answer5: "نعم، يتضمن كامل تطبيقات جوال لكل من iOS و Android لجميع الخطط. يمكن لفريقك إدارة العمليات أثناء التنقل، ويمكن للحجاج الوصول إلى معلوماتهم من خلال تطبيق حاج مخصص.",
            question6: "ما مدى أمان بياناتنا؟",
            answer6: "الأمان هو أولويتنا القصوى. نستخدم تشفيراً على مستوى المؤسسات وعمليات تدقيق أمنية منتظمة ونلتزم بمعايير حماية البيانات الدولية. يتم نسخ جميع البيانات احتياطياً يومياً مع بروتوكولات استعادة الكوارث المعمول بها."
        },
        contact: {
            tag: "تواصل معنا",
            title: "دعنا نناقش احتياجاتك",
            subtitle: "حدد موعد استشارة مع فريقنا لمعرفة كيف يمكن لكامل تحويل عمليات الحج الخاصة بك",
            nameLabel: "الاسم الكامل",
            namePlaceholder: "اسمك الكامل",
            emailLabel: "عنوان البريد الإلكتروني",
            emailPlaceholder: "your@email.com",
            companyLabel: "الشركة/المنظمة",
            companyPlaceholder: "اسم شركتك",
            messageLabel: "الرسالة",
            messagePlaceholder: "أخبرنا عن احتياجاتك...",
            submitButton: "إرسال الرسالة",
            successMessage: "شكراً لك! سنعاود الاتصال بك قريباً.",
            errorMessage: "حدث خطأ ما. يرجى المحاولة مرة أخرى."
        },
        footer: {
            description: "تحويل عمليات الحج من خلال الحلول الرقمية المبتكرة.",
            quickLinksTitle: "روابط سريعة",
            features: "الميزات",
            solutions: "الحلول",
            pricing: "الأسعار",
            testimonials: "آراء العملاء",
            supportTitle: "الدعم",
            contact: "تواصل معنا",
            faq: "الأسئلة الشائعة",
            help: "مركز المساعدة",
            documentation: "التوثيق",
            legalTitle: "قانوني",
            privacy: "سياسة الخصوصية",
            terms: "شروط الخدمة",
            copyright: "© 2024 كامل. جميع الحقوق محفوظة."
        }
    }
};

