// Bilingual content for Kamel Landing Page
const content = {
    en: {
        nav: {
            logo: "Kamel",
            features: "Features",
            solutions: "Solutions",
            pricing: "Pricing",
            testimonials: "Testimonials",
            contact: "Contact",
            cta: "Request Demo"
        },
        hero: {
            headline: "Transform Your Hajj Operations",
            subheadline: "Complete digital platform for managing pilgrims, services, and quality standards throughout the entire Hajj journey.",
            primaryCta: "Get Started",
            secondaryCta: "Learn More",
            stat1Value: "500+",
            stat1Label: "Operators",
            stat2Value: "1M+",
            stat2Label: "Pilgrims Served",
            stat3Value: "99.9%",
            stat3Label: "Uptime"
        },
        features: {
            title: "Comprehensive Features",
            subtitle: "Everything you need to manage Hajj operations efficiently and professionally",
            feature1Title: "Operations Management",
            feature1Desc: "Centralize all operations with real-time tracking, automated workflows, and comprehensive dashboards.",
            feature2Title: "Housing & Transportation",
            feature2Desc: "Manage accommodations, bus schedules, and logistics with intelligent planning and optimization tools.",
            feature3Title: "Quality Compliance",
            feature3Desc: "Ensure adherence to government standards with automated checks, reports, and quality assurance workflows.",
            feature4Title: "Communication Tools",
            feature4Desc: "Keep everyone connected with multi-channel messaging, notifications, and real-time updates."
        },
        solutions: {
            title: "Solutions for Every Challenge",
            subtitle: "Purpose-built tools to address the unique challenges of Hajj operations",
            solution1Tag: "Problem",
            solution1Title: "Scattered Information Across Multiple Systems",
            solution1Problem: "Hajj operators struggle with managing data across spreadsheets, emails, and disconnected tools, leading to errors and inefficiencies.",
            solution1SolutionTag: "Solution",
            solution1Solution: "Kamel unifies all operations in one centralized platform with real-time data synchronization and intelligent automation.",
            solution1Benefit1: "Single source of truth for all operations data",
            solution1Benefit2: "Automated workflows eliminate manual data entry",
            solution1Benefit3: "Real-time visibility across all teams and locations",
            solution2Tag: "Problem",
            solution2Title: "Complex Logistics and Coordination Challenges",
            solution2Problem: "Managing transportation, accommodations, and schedules for thousands of pilgrims requires precise coordination and real-time adjustments.",
            solution2SolutionTag: "Solution",
            solution2Solution: "Smart logistics management with GPS tracking, capacity planning, and automated scheduling optimization.",
            solution2Benefit1: "Real-time bus and vehicle tracking",
            solution2Benefit2: "Intelligent room allocation and capacity management",
            solution2Benefit3: "Automated schedule adjustments and notifications",
            solution3Tag: "Problem",
            solution3Title: "Meeting Government Standards and Regulations",
            solution3Problem: "Complying with Ministry requirements and quality standards demands extensive documentation and regular audits.",
            solution3SolutionTag: "Solution",
            solution3Solution: "Built-in compliance framework with automated reporting, quality checklists, and audit trail management.",
            solution3Benefit1: "Pre-configured compliance templates",
            solution3Benefit2: "Automatic report generation for authorities",
            solution3Benefit3: "Complete audit trail for all operations"
        },
        testimonials: {
            title: "Trusted by Hajj Operators",
            subtitle: "See what our clients say about transforming their operations with Kamel",
            testimonial1Name: "Ahmed Al-Rashid",
            testimonial1Title: "Operations Director",
            testimonial1Company: "Al-Noor Hajj Services",
            testimonial1Quote: "Kamel has revolutionized how we manage our Hajj operations. The real-time tracking and automated workflows have reduced our operational costs by 40% while improving service quality.",
            testimonial2Name: "Fatima Al-Zahrani",
            testimonial2Title: "CEO",
            testimonial2Company: "Excellence Hajj Group",
            testimonial2Quote: "The compliance features alone are worth it. We now generate all required reports automatically and have complete confidence in meeting government standards. Highly recommended!",
            testimonial3Name: "Mohammed bin Saud",
            testimonial3Title: "Logistics Manager",
            testimonial3Company: "Premium Hajj Solutions",
            testimonial3Quote: "Transportation management has never been easier. We track all our buses in real-time and our pilgrims receive automatic updates. Customer satisfaction has improved dramatically."
        },
        pricing: {
            title: "Flexible Pricing Plans",
            subtitle: "Choose the plan that fits your organization's needs",
            popularBadge: "Most Popular",
            plan1Name: "Starter",
            plan1Desc: "Perfect for small operators",
            plan1Price: "$499",
            plan1Period: "/month",
            plan1Feature1: "Up to 1,000 pilgrims",
            plan1Feature2: "Basic operations management",
            plan1Feature3: "Email support",
            plan1Feature4: "Mobile app access",
            plan1Cta: "Get Started",
            plan2Name: "Professional",
            plan2Desc: "For growing organizations",
            plan2Price: "$999",
            plan2Period: "/month",
            plan2Feature1: "Up to 5,000 pilgrims",
            plan2Feature2: "Advanced operations & logistics",
            plan2Feature3: "Priority support 24/7",
            plan2Feature4: "GPS tracking & analytics",
            plan2Feature5: "API access",
            plan2Cta: "Get Started",
            plan3Name: "Enterprise",
            plan3Desc: "For large-scale operations",
            plan3Price: "Custom",
            plan3Feature1: "Unlimited pilgrims",
            plan3Feature2: "Full platform customization",
            plan3Feature3: "Dedicated account manager",
            plan3Feature4: "On-premise deployment option",
            plan3Feature5: "Custom integrations",
            plan3Cta: "Contact Sales"
        },
        faq: {
            title: "Frequently Asked Questions",
            subtitle: "Get answers to common questions about Kamel",
            question1: "How quickly can we implement Kamel?",
            answer1: "Implementation typically takes 2-4 weeks depending on your organization's size and complexity. Our team provides full onboarding support, training, and data migration assistance to ensure a smooth transition.",
            question2: "Is Kamel compliant with Saudi government regulations?",
            answer2: "Yes, Kamel is fully compliant with Ministry of Hajj and Umrah regulations. We regularly update our platform to meet all government standards and requirements for Hajj service providers.",
            question3: "Can we integrate Kamel with our existing systems?",
            answer3: "Absolutely. Kamel offers API access for Professional and Enterprise plans, allowing seamless integration with your existing CRM, accounting, and other business systems.",
            question4: "What kind of support do you provide?",
            answer4: "We offer email support for all plans, with 24/7 priority support for Professional and Enterprise customers. Enterprise clients also receive a dedicated account manager and on-site training if needed.",
            question5: "Is mobile access included?",
            answer5: "Yes, Kamel includes mobile apps for both iOS and Android for all plans. Your team can manage operations on the go, and pilgrims can access their information through a dedicated pilgrim app.",
            question6: "How secure is our data?",
            answer6: "Security is our top priority. We use enterprise-grade encryption, regular security audits, and comply with international data protection standards. All data is backed up daily with disaster recovery protocols in place."
        },
        contact: {
            title: "Get Started Today",
            subtitle: "Contact us to schedule a demo and see how Kamel can transform your operations",
            nameLabel: "Full Name",
            namePlaceholder: "Your full name",
            emailLabel: "Email Address",
            emailPlaceholder: "your@email.com",
            companyLabel: "Company/Organization",
            companyPlaceholder: "Your company name",
            messageLabel: "Message",
            messagePlaceholder: "Tell us about your needs...",
            submitButton: "Send Message",
            successMessage: "Thank you! We'll get back to you shortly.",
            errorMessage: "Something went wrong. Please try again."
        },
        footer: {
            description: "Transforming Hajj operations through innovative digital solutions.",
            quickLinksTitle: "Quick Links",
            features: "Features",
            solutions: "Solutions",
            pricing: "Pricing",
            testimonials: "Testimonials",
            supportTitle: "Support",
            contact: "Contact Us",
            faq: "FAQ",
            help: "Help Center",
            documentation: "Documentation",
            legalTitle: "Legal",
            privacy: "Privacy Policy",
            terms: "Terms of Service",
            copyright: "© 2024 Kamel. All rights reserved."
        }
    },
    ar: {
        nav: {
            logo: "كامل",
            features: "الميزات",
            solutions: "الحلول",
            pricing: "الأسعار",
            testimonials: "آراء العملاء",
            contact: "تواصل معنا",
            cta: "طلب عرض توضيحي"
        },
        hero: {
            headline: "حوّل عمليات الحج لديك",
            subheadline: "منصة رقمية شاملة لإدارة الحجاج والخدمات ومعايير الجودة طوال رحلة الحج بأكملها.",
            primaryCta: "ابدأ الآن",
            secondaryCta: "اعرف المزيد",
            stat1Value: "500+",
            stat1Label: "مشغل",
            stat2Value: "1+ مليون",
            stat2Label: "حاج تمت خدمته",
            stat3Value: "99.9%",
            stat3Label: "وقت التشغيل"
        },
        features: {
            title: "ميزات شاملة",
            subtitle: "كل ما تحتاجه لإدارة عمليات الحج بكفاءة واحترافية",
            feature1Title: "إدارة العمليات",
            feature1Desc: "مركزية جميع العمليات مع التتبع في الوقت الفعلي وسير العمل الآلي ولوحات المعلومات الشاملة.",
            feature2Title: "الإسكان والنقل",
            feature2Desc: "إدارة أماكن الإقامة وجداول الحافلات والخدمات اللوجستية باستخدام أدوات التخطيط والتحسين الذكية.",
            feature3Title: "الامتثال للجودة",
            feature3Desc: "ضمان الالتزام بالمعايير الحكومية من خلال الفحوصات الآلية والتقارير وسير عمل ضمان الجودة.",
            feature4Title: "أدوات التواصل",
            feature4Desc: "إبقاء الجميع على اتصال مع المراسلة متعددة القنوات والإشعارات والتحديثات في الوقت الفعلي."
        },
        solutions: {
            title: "حلول لكل تحدي",
            subtitle: "أدوات مصممة خصيصاً لمواجهة التحديات الفريدة لعمليات الحج",
            solution1Tag: "المشكلة",
            solution1Title: "تشتت المعلومات عبر أنظمة متعددة",
            solution1Problem: "يواجه مشغلو الحج صعوبة في إدارة البيانات عبر جداول البيانات والبريد الإلكتروني والأدوات غير المتصلة، مما يؤدي إلى أخطاء وعدم كفاءة.",
            solution1SolutionTag: "الحل",
            solution1Solution: "يوحد كامل جميع العمليات في منصة مركزية واحدة مع مزامنة البيانات في الوقت الفعلي والأتمتة الذكية.",
            solution1Benefit1: "مصدر واحد للحقيقة لجميع بيانات العمليات",
            solution1Benefit2: "سير العمل الآلي يلغي إدخال البيانات يدوياً",
            solution1Benefit3: "رؤية في الوقت الفعلي عبر جميع الفرق والمواقع",
            solution2Tag: "المشكلة",
            solution2Title: "تحديات الخدمات اللوجستية والتنسيق المعقدة",
            solution2Problem: "تتطلب إدارة النقل والإقامة والجداول الزمنية لآلاف الحجاج تنسيقاً دقيقاً وتعديلات في الوقت الفعلي.",
            solution2SolutionTag: "الحل",
            solution2Solution: "إدارة لوجستية ذكية مع تتبع GPS وتخطيط القدرات وتحسين الجدولة الآلية.",
            solution2Benefit1: "تتبع الحافلات والمركبات في الوقت الفعلي",
            solution2Benefit2: "تخصيص ذكي للغرف وإدارة السعة",
            solution2Benefit3: "تعديلات تلقائية للجدول الزمني والإشعارات",
            solution3Tag: "المشكلة",
            solution3Title: "الامتثال للمعايير واللوائح الحكومية",
            solution3Problem: "يتطلب الامتثال لمتطلبات الوزارة ومعايير الجودة توثيقاً واسع النطاق وعمليات تدقيق منتظمة.",
            solution3SolutionTag: "الحل",
            solution3Solution: "إطار امتثال مدمج مع إعداد التقارير الآلية وقوائم التحقق من الجودة وإدارة سجل التدقيق.",
            solution3Benefit1: "قوالب امتثال مُعدة مسبقاً",
            solution3Benefit2: "إنشاء تقارير تلقائية للسلطات",
            solution3Benefit3: "سجل تدقيق كامل لجميع العمليات"
        },
        testimonials: {
            title: "موثوق به من قبل مشغلي الحج",
            subtitle: "اطلع على ما يقوله عملاؤنا حول تحويل عملياتهم مع كامل",
            testimonial1Name: "أحمد الراشد",
            testimonial1Title: "مدير العمليات",
            testimonial1Company: "خدمات الحج النور",
            testimonial1Quote: "لقد أحدث كامل ثورة في كيفية إدارتنا لعمليات الحج. لقد قلل التتبع في الوقت الفعلي وسير العمل الآلي من تكاليف التشغيل بنسبة 40٪ مع تحسين جودة الخدمة.",
            testimonial2Name: "فاطمة الزهراني",
            testimonial2Title: "الرئيس التنفيذي",
            testimonial2Company: "مجموعة الحج المتميزة",
            testimonial2Quote: "ميزات الامتثال وحدها تستحق ذلك. نحن الآن ننشئ جميع التقارير المطلوبة تلقائياً ولدينا ثقة كاملة في تلبية المعايير الحكومية. موصى به بشدة!",
            testimonial3Name: "محمد بن سعود",
            testimonial3Title: "مدير اللوجستيات",
            testimonial3Company: "حلول الحج الممتازة",
            testimonial3Quote: "لم تكن إدارة النقل أسهل من أي وقت مضى. نتتبع جميع حافلاتنا في الوقت الفعلي ويتلقى حجاجنا تحديثات تلقائية. تحسنت رضا العملاء بشكل كبير."
        },
        pricing: {
            title: "خطط تسعير مرنة",
            subtitle: "اختر الخطة التي تناسب احتياجات مؤسستك",
            popularBadge: "الأكثر شيوعاً",
            plan1Name: "المبتدئ",
            plan1Desc: "مثالي للمشغلين الصغار",
            plan1Price: "499$",
            plan1Period: "/شهر",
            plan1Feature1: "ما يصل إلى 1,000 حاج",
            plan1Feature2: "إدارة العمليات الأساسية",
            plan1Feature3: "دعم البريد الإلكتروني",
            plan1Feature4: "الوصول إلى تطبيق الجوال",
            plan1Cta: "ابدأ الآن",
            plan2Name: "المحترف",
            plan2Desc: "للمنظمات المتنامية",
            plan2Price: "999$",
            plan2Period: "/شهر",
            plan2Feature1: "ما يصل إلى 5,000 حاج",
            plan2Feature2: "عمليات ولوجستيات متقدمة",
            plan2Feature3: "دعم ذو أولوية 24/7",
            plan2Feature4: "تتبع GPS والتحليلات",
            plan2Feature5: "الوصول إلى API",
            plan2Cta: "ابدأ الآن",
            plan3Name: "المؤسسات",
            plan3Desc: "للعمليات واسعة النطاق",
            plan3Price: "مخصص",
            plan3Feature1: "حجاج غير محدودين",
            plan3Feature2: "تخصيص كامل للمنصة",
            plan3Feature3: "مدير حساب مخصص",
            plan3Feature4: "خيار النشر المحلي",
            plan3Feature5: "تكاملات مخصصة",
            plan3Cta: "تواصل مع المبيعات"
        },
        faq: {
            title: "الأسئلة الشائعة",
            subtitle: "احصل على إجابات للأسئلة الشائعة حول كامل",
            question1: "ما مدى سرعة تنفيذ كامل؟",
            answer1: "يستغرق التنفيذ عادةً من 2 إلى 4 أسابيع حسب حجم مؤسستك وتعقيدها. يقدم فريقنا دعماً كاملاً للتأهيل والتدريب ومساعدة في ترحيل البيانات لضمان انتقال سلس.",
            question2: "هل كامل متوافق مع اللوائح الحكومية السعودية؟",
            answer2: "نعم، كامل متوافق تماماً مع لوائح وزارة الحج والعمرة. نقوم بتحديث منصتنا بانتظام لتلبية جميع المعايير والمتطلبات الحكومية لمقدمي خدمات الحج.",
            question3: "هل يمكننا دمج كامل مع أنظمتنا الحالية؟",
            answer3: "بالتأكيد. يوفر كامل وصولاً إلى API للخطط الاحترافية والمؤسسية، مما يسمح بالتكامل السلس مع أنظمة CRM والمحاسبة والأعمال الأخرى الموجودة لديك.",
            question4: "ما نوع الدعم الذي تقدمونه؟",
            answer4: "نقدم دعماً عبر البريد الإلكتروني لجميع الخطط، مع دعم ذو أولوية على مدار الساعة طوال أيام الأسبوع للعملاء المحترفين والمؤسسيين. يتلقى عملاء المؤسسات أيضاً مدير حساب مخصص وتدريب في الموقع إذا لزم الأمر.",
            question5: "هل الوصول عبر الهاتف المحمول مشمول؟",
            answer5: "نعم، يتضمن كامل تطبيقات جوال لكل من iOS و Android لجميع الخطط. يمكن لفريقك إدارة العمليات أثناء التنقل، ويمكن للحجاج الوصول إلى معلوماتهم من خلال تطبيق حاج مخصص.",
            question6: "ما مدى أمان بياناتنا؟",
            answer6: "الأمان هو أولويتنا القصوى. نستخدم تشفيراً على مستوى المؤسسات وعمليات تدقيق أمنية منتظمة ونلتزم بمعايير حماية البيانات الدولية. يتم نسخ جميع البيانات احتياطياً يومياً مع بروتوكولات استعادة الكوارث المعمول بها."
        },
        contact: {
            title: "ابدأ اليوم",
            subtitle: "تواصل معنا لجدولة عرض توضيحي واكتشف كيف يمكن لكامل تحويل عملياتك",
            nameLabel: "الاسم الكامل",
            namePlaceholder: "اسمك الكامل",
            emailLabel: "عنوان البريد الإلكتروني",
            emailPlaceholder: "your@email.com",
            companyLabel: "الشركة/المنظمة",
            companyPlaceholder: "اسم شركتك",
            messageLabel: "الرسالة",
            messagePlaceholder: "أخبرنا عن احتياجاتك...",
            submitButton: "إرسال الرسالة",
            successMessage: "شكراً لك! سنعاود الاتصال بك قريباً.",
            errorMessage: "حدث خطأ ما. يرجى المحاولة مرة أخرى."
        },
        footer: {
            description: "تحويل عمليات الحج من خلال الحلول الرقمية المبتكرة.",
            quickLinksTitle: "روابط سريعة",
            features: "الميزات",
            solutions: "الحلول",
            pricing: "الأسعار",
            testimonials: "آراء العملاء",
            supportTitle: "الدعم",
            contact: "تواصل معنا",
            faq: "الأسئلة الشائعة",
            help: "مركز المساعدة",
            documentation: "التوثيق",
            legalTitle: "قانوني",
            privacy: "سياسة الخصوصية",
            terms: "شروط الخدمة",
            copyright: "© 2024 كامل. جميع الحقوق محفوظة."
        }
    }
};

